package me.tomkent.chemcraft;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;
import me.tomkent.chemcraft.Items.*;

public class ItemLoader {
		public static Item dustActinium;
		public static Item dustAluminium;
		public static Item dustAntimony;
		public static Item dustArsenic;
		public static Item dustBarium;
		public static Item dustBeryllium;
		public static Item dustBismuth;
		public static Item dustBoron;
		public static Item dustCadmium;
		public static Item dustCaesium;
		public static Item dustCalcium;
		public static Item dustCarbon;
		public static Item dustCerium;
		public static Item dustChromium;
		public static Item dustCobalt;
		public static Item dustCopper;
		public static Item dustDysprosium;
		public static Item dustErbium;
		public static Item dustEuropium;
		public static Item dustGadolinium;
		public static Item dustGallium;
		public static Item dustGermanium;
		public static Item dustGold;
		public static Item dustHafnium;
		public static Item dustHolmium;
		public static Item dustIndium;
		public static Item dustIodine;
		public static Item dustIridium;
		public static Item dustIron;
		public static Item dustKrypton;
		public static Item dustLanthanum;
		public static Item dustLead;
		public static Item dustLithium;
		public static Item dustLutetium;
		public static Item dustMagnesium;
		public static Item dustManganese;
		public static Item dustMercury;
		public static Item dustMolybdenum;
		public static Item dustNeodymium;
		public static Item dustNickel;
		public static Item dustNiobium;
		public static Item dustOsmium;
		public static Item dustPalladium;
		public static Item dustPhosphorus;
		public static Item dustPlatinum;
		public static Item dustPolonium;
		public static Item dustPotassium;
		public static Item dustPraseodymium;
		public static Item dustProtactinium;
		public static Item dustRadium;
		public static Item dustRhenium;
		public static Item dustRhodium;
		public static Item dustRubidium;
		public static Item dustRuthenium;
		public static Item dustSamarium;
		public static Item dustScandium;
		public static Item dustSelenium;
		public static Item dustSilicon;
		public static Item dustSilver;
		public static Item dustSodium;
		public static Item dustStrontium;
		public static Item dustSulfur;
		public static Item dustTantalum;
		public static Item dustTellurium;
		public static Item dustTerbium;
		public static Item dustThallium;
		public static Item dustThorium;
		public static Item dustThulium;
		public static Item dustTin;
		public static Item dustTitanium;
		public static Item dustTungsten;
		public static Item dustUranium;
		public static Item dustVanadium;
		public static Item dustYtterbium;
		public static Item dustYttrium;
		public static Item dustZinc;
		public static Item dustZirconium;
		public static Item ingotActinium;
		public static Item ingotAluminium;
		public static Item ingotAntimony;
		public static Item ingotArsenic;
		public static Item ingotBarium;
		public static Item ingotBeryllium;
		public static Item ingotBismuth;
		public static Item ingotBoron;
		public static Item ingotCadmium;
		public static Item ingotCaesium;
		public static Item ingotCalcium;
		public static Item ingotCerium;
		public static Item ingotChromium;
		public static Item ingotCobalt;
		public static Item ingotCopper;
		public static Item ingotDysprosium;
		public static Item ingotErbium;
		public static Item ingotEuropium;
		public static Item ingotGadolinium;
		public static Item ingotGallium;
		public static Item ingotGermanium;
		public static Item ingotGold;
		public static Item ingotHafnium;
		public static Item ingotHolmium;
		public static Item ingotIndium;
		public static Item ingotIodine;
		public static Item ingotIridium;
		public static Item ingotIron;
		public static Item ingotKrypton;
		public static Item ingotLanthanum;
		public static Item ingotLead;
		public static Item ingotLithium;
		public static Item ingotLutetium;
		public static Item ingotMagnesium;
		public static Item ingotManganese;
		public static Item ingotMercury;
		public static Item ingotMolybdenum;
		public static Item ingotNeodymium;
		public static Item ingotNickel;
		public static Item ingotNiobium;
		public static Item ingotOsmium;
		public static Item ingotPalladium;
		public static Item ingotPhosphorus;
		public static Item ingotPlatinum;
		public static Item ingotPolonium;
		public static Item ingotPotassium;
		public static Item ingotPraseodymium;
		public static Item ingotProtactinium;
		public static Item ingotRadium;
		public static Item ingotRhenium;
		public static Item ingotRhodium;
		public static Item ingotRubidium;
		public static Item ingotRuthenium;
		public static Item ingotSamarium;
		public static Item ingotScandium;
		public static Item ingotSelenium;
		public static Item ingotSilicon;
		public static Item ingotSilver;
		public static Item ingotSodium;
		public static Item ingotStrontium;
		public static Item ingotTantalum;
		public static Item ingotTellurium;
		public static Item ingotTerbium;
		public static Item ingotThallium;
		public static Item ingotThorium;
		public static Item ingotThulium;
		public static Item ingotTin;
		public static Item ingotTitanium;
		public static Item ingotTungsten;
		public static Item ingotUranium;
		public static Item ingotVanadium;
		public static Item ingotYtterbium;
		public static Item ingotYttrium;
		public static Item ingotZinc;
		public static Item ingotZirconium;
		public static Item plateActinium;
		public static Item plateAluminium;
		public static Item plateAntimony;
		public static Item plateArsenic;
		public static Item plateBarium;
		public static Item plateBeryllium;
		public static Item plateBismuth;
		public static Item plateBoron;
		public static Item plateCadmium;
		public static Item plateCaesium;
		public static Item plateCarbon;
		public static Item plateCerium;
		public static Item plateChromium;
		public static Item plateCobalt;
		public static Item plateCopper;
		public static Item plateDysprosium;
		public static Item plateErbium;
		public static Item plateEuropium;
		public static Item plateGadolinium;
		public static Item plateGallium;
		public static Item plateGermanium;
		public static Item plateGold;
		public static Item plateHafnium;
		public static Item plateHolmium;
		public static Item plateIndium;
		public static Item plateIodine;
		public static Item plateIridium;
		public static Item plateIron;
		public static Item plateKrypton;
		public static Item plateLanthanum;
		public static Item plateLead;
		public static Item plateLithium;
		public static Item plateLutetium;
		public static Item plateMagnesium;
		public static Item plateManganese;
		public static Item plateMercury;
		public static Item plateMolybdenum;
		public static Item plateNeodymium;
		public static Item plateNickel;
		public static Item plateNiobium;
		public static Item plateOsmium;
		public static Item platePalladium;
		public static Item platePhosphorus;
		public static Item platePlatinum;
		public static Item platePolonium;
		public static Item platePotassium;
		public static Item platePraseodymium;
		public static Item plateProtactinium;
		public static Item plateRadium;
		public static Item plateRhenium;
		public static Item plateRhodium;
		public static Item plateRubidium;
		public static Item plateRuthenium;
		public static Item plateSamarium;
		public static Item plateScandium;
		public static Item plateSelenium;
		public static Item plateSilicon;
		public static Item plateSilver;
		public static Item plateSodium;
		public static Item plateStrontium;
		public static Item plateSulfur;
		public static Item plateTantalum;
		public static Item plateTellurium;
		public static Item plateTerbium;
		public static Item plateThallium;
		public static Item plateThorium;
		public static Item plateThulium;
		public static Item plateTin;
		public static Item plateTitanium;
		public static Item plateTungsten;
		public static Item plateUranium;
		public static Item plateVanadium;
		public static Item plateYtterbium;
		public static Item plateYttrium;
		public static Item plateZinc;
		public static Item plateZirconium;
		
	
	public static void initItems() {
				dustActinium = new dustActinium();
		GameRegistry.registerItem(dustActinium, "dustActinium");
				dustAluminium = new dustAluminium();
		GameRegistry.registerItem(dustAluminium, "dustAluminium");
				dustAntimony = new dustAntimony();
		GameRegistry.registerItem(dustAntimony, "dustAntimony");
				dustArsenic = new dustArsenic();
		GameRegistry.registerItem(dustArsenic, "dustArsenic");
				dustBarium = new dustBarium();
		GameRegistry.registerItem(dustBarium, "dustBarium");
				dustBeryllium = new dustBeryllium();
		GameRegistry.registerItem(dustBeryllium, "dustBeryllium");
				dustBismuth = new dustBismuth();
		GameRegistry.registerItem(dustBismuth, "dustBismuth");
				dustBoron = new dustBoron();
		GameRegistry.registerItem(dustBoron, "dustBoron");
				dustCadmium = new dustCadmium();
		GameRegistry.registerItem(dustCadmium, "dustCadmium");
				dustCaesium = new dustCaesium();
		GameRegistry.registerItem(dustCaesium, "dustCaesium");
				dustCalcium = new dustCalcium();
		GameRegistry.registerItem(dustCalcium, "dustCalcium");
				dustCarbon = new dustCarbon();
		GameRegistry.registerItem(dustCarbon, "dustCarbon");
				dustCerium = new dustCerium();
		GameRegistry.registerItem(dustCerium, "dustCerium");
				dustChromium = new dustChromium();
		GameRegistry.registerItem(dustChromium, "dustChromium");
				dustCobalt = new dustCobalt();
		GameRegistry.registerItem(dustCobalt, "dustCobalt");
				dustCopper = new dustCopper();
		GameRegistry.registerItem(dustCopper, "dustCopper");
				dustDysprosium = new dustDysprosium();
		GameRegistry.registerItem(dustDysprosium, "dustDysprosium");
				dustErbium = new dustErbium();
		GameRegistry.registerItem(dustErbium, "dustErbium");
				dustEuropium = new dustEuropium();
		GameRegistry.registerItem(dustEuropium, "dustEuropium");
				dustGadolinium = new dustGadolinium();
		GameRegistry.registerItem(dustGadolinium, "dustGadolinium");
				dustGallium = new dustGallium();
		GameRegistry.registerItem(dustGallium, "dustGallium");
				dustGermanium = new dustGermanium();
		GameRegistry.registerItem(dustGermanium, "dustGermanium");
				dustGold = new dustGold();
		GameRegistry.registerItem(dustGold, "dustGold");
				dustHafnium = new dustHafnium();
		GameRegistry.registerItem(dustHafnium, "dustHafnium");
				dustHolmium = new dustHolmium();
		GameRegistry.registerItem(dustHolmium, "dustHolmium");
				dustIndium = new dustIndium();
		GameRegistry.registerItem(dustIndium, "dustIndium");
				dustIodine = new dustIodine();
		GameRegistry.registerItem(dustIodine, "dustIodine");
				dustIridium = new dustIridium();
		GameRegistry.registerItem(dustIridium, "dustIridium");
				dustIron = new dustIron();
		GameRegistry.registerItem(dustIron, "dustIron");
				dustKrypton = new dustKrypton();
		GameRegistry.registerItem(dustKrypton, "dustKrypton");
				dustLanthanum = new dustLanthanum();
		GameRegistry.registerItem(dustLanthanum, "dustLanthanum");
				dustLead = new dustLead();
		GameRegistry.registerItem(dustLead, "dustLead");
				dustLithium = new dustLithium();
		GameRegistry.registerItem(dustLithium, "dustLithium");
				dustLutetium = new dustLutetium();
		GameRegistry.registerItem(dustLutetium, "dustLutetium");
				dustMagnesium = new dustMagnesium();
		GameRegistry.registerItem(dustMagnesium, "dustMagnesium");
				dustManganese = new dustManganese();
		GameRegistry.registerItem(dustManganese, "dustManganese");
				dustMercury = new dustMercury();
		GameRegistry.registerItem(dustMercury, "dustMercury");
				dustMolybdenum = new dustMolybdenum();
		GameRegistry.registerItem(dustMolybdenum, "dustMolybdenum");
				dustNeodymium = new dustNeodymium();
		GameRegistry.registerItem(dustNeodymium, "dustNeodymium");
				dustNickel = new dustNickel();
		GameRegistry.registerItem(dustNickel, "dustNickel");
				dustNiobium = new dustNiobium();
		GameRegistry.registerItem(dustNiobium, "dustNiobium");
				dustOsmium = new dustOsmium();
		GameRegistry.registerItem(dustOsmium, "dustOsmium");
				dustPalladium = new dustPalladium();
		GameRegistry.registerItem(dustPalladium, "dustPalladium");
				dustPhosphorus = new dustPhosphorus();
		GameRegistry.registerItem(dustPhosphorus, "dustPhosphorus");
				dustPlatinum = new dustPlatinum();
		GameRegistry.registerItem(dustPlatinum, "dustPlatinum");
				dustPolonium = new dustPolonium();
		GameRegistry.registerItem(dustPolonium, "dustPolonium");
				dustPotassium = new dustPotassium();
		GameRegistry.registerItem(dustPotassium, "dustPotassium");
				dustPraseodymium = new dustPraseodymium();
		GameRegistry.registerItem(dustPraseodymium, "dustPraseodymium");
				dustProtactinium = new dustProtactinium();
		GameRegistry.registerItem(dustProtactinium, "dustProtactinium");
				dustRadium = new dustRadium();
		GameRegistry.registerItem(dustRadium, "dustRadium");
				dustRhenium = new dustRhenium();
		GameRegistry.registerItem(dustRhenium, "dustRhenium");
				dustRhodium = new dustRhodium();
		GameRegistry.registerItem(dustRhodium, "dustRhodium");
				dustRubidium = new dustRubidium();
		GameRegistry.registerItem(dustRubidium, "dustRubidium");
				dustRuthenium = new dustRuthenium();
		GameRegistry.registerItem(dustRuthenium, "dustRuthenium");
				dustSamarium = new dustSamarium();
		GameRegistry.registerItem(dustSamarium, "dustSamarium");
				dustScandium = new dustScandium();
		GameRegistry.registerItem(dustScandium, "dustScandium");
				dustSelenium = new dustSelenium();
		GameRegistry.registerItem(dustSelenium, "dustSelenium");
				dustSilicon = new dustSilicon();
		GameRegistry.registerItem(dustSilicon, "dustSilicon");
				dustSilver = new dustSilver();
		GameRegistry.registerItem(dustSilver, "dustSilver");
				dustSodium = new dustSodium();
		GameRegistry.registerItem(dustSodium, "dustSodium");
				dustStrontium = new dustStrontium();
		GameRegistry.registerItem(dustStrontium, "dustStrontium");
				dustSulfur = new dustSulfur();
		GameRegistry.registerItem(dustSulfur, "dustSulfur");
				dustTantalum = new dustTantalum();
		GameRegistry.registerItem(dustTantalum, "dustTantalum");
				dustTellurium = new dustTellurium();
		GameRegistry.registerItem(dustTellurium, "dustTellurium");
				dustTerbium = new dustTerbium();
		GameRegistry.registerItem(dustTerbium, "dustTerbium");
				dustThallium = new dustThallium();
		GameRegistry.registerItem(dustThallium, "dustThallium");
				dustThorium = new dustThorium();
		GameRegistry.registerItem(dustThorium, "dustThorium");
				dustThulium = new dustThulium();
		GameRegistry.registerItem(dustThulium, "dustThulium");
				dustTin = new dustTin();
		GameRegistry.registerItem(dustTin, "dustTin");
				dustTitanium = new dustTitanium();
		GameRegistry.registerItem(dustTitanium, "dustTitanium");
				dustTungsten = new dustTungsten();
		GameRegistry.registerItem(dustTungsten, "dustTungsten");
				dustUranium = new dustUranium();
		GameRegistry.registerItem(dustUranium, "dustUranium");
				dustVanadium = new dustVanadium();
		GameRegistry.registerItem(dustVanadium, "dustVanadium");
				dustYtterbium = new dustYtterbium();
		GameRegistry.registerItem(dustYtterbium, "dustYtterbium");
				dustYttrium = new dustYttrium();
		GameRegistry.registerItem(dustYttrium, "dustYttrium");
				dustZinc = new dustZinc();
		GameRegistry.registerItem(dustZinc, "dustZinc");
				dustZirconium = new dustZirconium();
		GameRegistry.registerItem(dustZirconium, "dustZirconium");
				ingotActinium = new ingotActinium();
		GameRegistry.registerItem(ingotActinium, "ingotActinium");
				ingotAluminium = new ingotAluminium();
		GameRegistry.registerItem(ingotAluminium, "ingotAluminium");
				ingotAntimony = new ingotAntimony();
		GameRegistry.registerItem(ingotAntimony, "ingotAntimony");
				ingotArsenic = new ingotArsenic();
		GameRegistry.registerItem(ingotArsenic, "ingotArsenic");
				ingotBarium = new ingotBarium();
		GameRegistry.registerItem(ingotBarium, "ingotBarium");
				ingotBeryllium = new ingotBeryllium();
		GameRegistry.registerItem(ingotBeryllium, "ingotBeryllium");
				ingotBismuth = new ingotBismuth();
		GameRegistry.registerItem(ingotBismuth, "ingotBismuth");
				ingotBoron = new ingotBoron();
		GameRegistry.registerItem(ingotBoron, "ingotBoron");
				ingotCadmium = new ingotCadmium();
		GameRegistry.registerItem(ingotCadmium, "ingotCadmium");
				ingotCaesium = new ingotCaesium();
		GameRegistry.registerItem(ingotCaesium, "ingotCaesium");
				ingotCalcium = new ingotCalcium();
		GameRegistry.registerItem(ingotCalcium, "ingotCalcium");
				ingotCerium = new ingotCerium();
		GameRegistry.registerItem(ingotCerium, "ingotCerium");
				ingotChromium = new ingotChromium();
		GameRegistry.registerItem(ingotChromium, "ingotChromium");
				ingotCobalt = new ingotCobalt();
		GameRegistry.registerItem(ingotCobalt, "ingotCobalt");
				ingotCopper = new ingotCopper();
		GameRegistry.registerItem(ingotCopper, "ingotCopper");
				ingotDysprosium = new ingotDysprosium();
		GameRegistry.registerItem(ingotDysprosium, "ingotDysprosium");
				ingotErbium = new ingotErbium();
		GameRegistry.registerItem(ingotErbium, "ingotErbium");
				ingotEuropium = new ingotEuropium();
		GameRegistry.registerItem(ingotEuropium, "ingotEuropium");
				ingotGadolinium = new ingotGadolinium();
		GameRegistry.registerItem(ingotGadolinium, "ingotGadolinium");
				ingotGallium = new ingotGallium();
		GameRegistry.registerItem(ingotGallium, "ingotGallium");
				ingotGermanium = new ingotGermanium();
		GameRegistry.registerItem(ingotGermanium, "ingotGermanium");
				ingotGold = new ingotGold();
		GameRegistry.registerItem(ingotGold, "ingotGold");
				ingotHafnium = new ingotHafnium();
		GameRegistry.registerItem(ingotHafnium, "ingotHafnium");
				ingotHolmium = new ingotHolmium();
		GameRegistry.registerItem(ingotHolmium, "ingotHolmium");
				ingotIndium = new ingotIndium();
		GameRegistry.registerItem(ingotIndium, "ingotIndium");
				ingotIodine = new ingotIodine();
		GameRegistry.registerItem(ingotIodine, "ingotIodine");
				ingotIridium = new ingotIridium();
		GameRegistry.registerItem(ingotIridium, "ingotIridium");
				ingotIron = new ingotIron();
		GameRegistry.registerItem(ingotIron, "ingotIron");
				ingotKrypton = new ingotKrypton();
		GameRegistry.registerItem(ingotKrypton, "ingotKrypton");
				ingotLanthanum = new ingotLanthanum();
		GameRegistry.registerItem(ingotLanthanum, "ingotLanthanum");
				ingotLead = new ingotLead();
		GameRegistry.registerItem(ingotLead, "ingotLead");
				ingotLithium = new ingotLithium();
		GameRegistry.registerItem(ingotLithium, "ingotLithium");
				ingotLutetium = new ingotLutetium();
		GameRegistry.registerItem(ingotLutetium, "ingotLutetium");
				ingotMagnesium = new ingotMagnesium();
		GameRegistry.registerItem(ingotMagnesium, "ingotMagnesium");
				ingotManganese = new ingotManganese();
		GameRegistry.registerItem(ingotManganese, "ingotManganese");
				ingotMercury = new ingotMercury();
		GameRegistry.registerItem(ingotMercury, "ingotMercury");
				ingotMolybdenum = new ingotMolybdenum();
		GameRegistry.registerItem(ingotMolybdenum, "ingotMolybdenum");
				ingotNeodymium = new ingotNeodymium();
		GameRegistry.registerItem(ingotNeodymium, "ingotNeodymium");
				ingotNickel = new ingotNickel();
		GameRegistry.registerItem(ingotNickel, "ingotNickel");
				ingotNiobium = new ingotNiobium();
		GameRegistry.registerItem(ingotNiobium, "ingotNiobium");
				ingotOsmium = new ingotOsmium();
		GameRegistry.registerItem(ingotOsmium, "ingotOsmium");
				ingotPalladium = new ingotPalladium();
		GameRegistry.registerItem(ingotPalladium, "ingotPalladium");
				ingotPhosphorus = new ingotPhosphorus();
		GameRegistry.registerItem(ingotPhosphorus, "ingotPhosphorus");
				ingotPlatinum = new ingotPlatinum();
		GameRegistry.registerItem(ingotPlatinum, "ingotPlatinum");
				ingotPolonium = new ingotPolonium();
		GameRegistry.registerItem(ingotPolonium, "ingotPolonium");
				ingotPotassium = new ingotPotassium();
		GameRegistry.registerItem(ingotPotassium, "ingotPotassium");
				ingotPraseodymium = new ingotPraseodymium();
		GameRegistry.registerItem(ingotPraseodymium, "ingotPraseodymium");
				ingotProtactinium = new ingotProtactinium();
		GameRegistry.registerItem(ingotProtactinium, "ingotProtactinium");
				ingotRadium = new ingotRadium();
		GameRegistry.registerItem(ingotRadium, "ingotRadium");
				ingotRhenium = new ingotRhenium();
		GameRegistry.registerItem(ingotRhenium, "ingotRhenium");
				ingotRhodium = new ingotRhodium();
		GameRegistry.registerItem(ingotRhodium, "ingotRhodium");
				ingotRubidium = new ingotRubidium();
		GameRegistry.registerItem(ingotRubidium, "ingotRubidium");
				ingotRuthenium = new ingotRuthenium();
		GameRegistry.registerItem(ingotRuthenium, "ingotRuthenium");
				ingotSamarium = new ingotSamarium();
		GameRegistry.registerItem(ingotSamarium, "ingotSamarium");
				ingotScandium = new ingotScandium();
		GameRegistry.registerItem(ingotScandium, "ingotScandium");
				ingotSelenium = new ingotSelenium();
		GameRegistry.registerItem(ingotSelenium, "ingotSelenium");
				ingotSilicon = new ingotSilicon();
		GameRegistry.registerItem(ingotSilicon, "ingotSilicon");
				ingotSilver = new ingotSilver();
		GameRegistry.registerItem(ingotSilver, "ingotSilver");
				ingotSodium = new ingotSodium();
		GameRegistry.registerItem(ingotSodium, "ingotSodium");
				ingotStrontium = new ingotStrontium();
		GameRegistry.registerItem(ingotStrontium, "ingotStrontium");
				ingotTantalum = new ingotTantalum();
		GameRegistry.registerItem(ingotTantalum, "ingotTantalum");
				ingotTellurium = new ingotTellurium();
		GameRegistry.registerItem(ingotTellurium, "ingotTellurium");
				ingotTerbium = new ingotTerbium();
		GameRegistry.registerItem(ingotTerbium, "ingotTerbium");
				ingotThallium = new ingotThallium();
		GameRegistry.registerItem(ingotThallium, "ingotThallium");
				ingotThorium = new ingotThorium();
		GameRegistry.registerItem(ingotThorium, "ingotThorium");
				ingotThulium = new ingotThulium();
		GameRegistry.registerItem(ingotThulium, "ingotThulium");
				ingotTin = new ingotTin();
		GameRegistry.registerItem(ingotTin, "ingotTin");
				ingotTitanium = new ingotTitanium();
		GameRegistry.registerItem(ingotTitanium, "ingotTitanium");
				ingotTungsten = new ingotTungsten();
		GameRegistry.registerItem(ingotTungsten, "ingotTungsten");
				ingotUranium = new ingotUranium();
		GameRegistry.registerItem(ingotUranium, "ingotUranium");
				ingotVanadium = new ingotVanadium();
		GameRegistry.registerItem(ingotVanadium, "ingotVanadium");
				ingotYtterbium = new ingotYtterbium();
		GameRegistry.registerItem(ingotYtterbium, "ingotYtterbium");
				ingotYttrium = new ingotYttrium();
		GameRegistry.registerItem(ingotYttrium, "ingotYttrium");
				ingotZinc = new ingotZinc();
		GameRegistry.registerItem(ingotZinc, "ingotZinc");
				ingotZirconium = new ingotZirconium();
		GameRegistry.registerItem(ingotZirconium, "ingotZirconium");
				plateActinium = new plateActinium();
		GameRegistry.registerItem(plateActinium, "plateActinium");
				plateAluminium = new plateAluminium();
		GameRegistry.registerItem(plateAluminium, "plateAluminium");
				plateAntimony = new plateAntimony();
		GameRegistry.registerItem(plateAntimony, "plateAntimony");
				plateArsenic = new plateArsenic();
		GameRegistry.registerItem(plateArsenic, "plateArsenic");
				plateBarium = new plateBarium();
		GameRegistry.registerItem(plateBarium, "plateBarium");
				plateBeryllium = new plateBeryllium();
		GameRegistry.registerItem(plateBeryllium, "plateBeryllium");
				plateBismuth = new plateBismuth();
		GameRegistry.registerItem(plateBismuth, "plateBismuth");
				plateBoron = new plateBoron();
		GameRegistry.registerItem(plateBoron, "plateBoron");
				plateCadmium = new plateCadmium();
		GameRegistry.registerItem(plateCadmium, "plateCadmium");
				plateCaesium = new plateCaesium();
		GameRegistry.registerItem(plateCaesium, "plateCaesium");
				plateCarbon = new plateCarbon();
		GameRegistry.registerItem(plateCarbon, "plateCarbon");
				plateCerium = new plateCerium();
		GameRegistry.registerItem(plateCerium, "plateCerium");
				plateChromium = new plateChromium();
		GameRegistry.registerItem(plateChromium, "plateChromium");
				plateCobalt = new plateCobalt();
		GameRegistry.registerItem(plateCobalt, "plateCobalt");
				plateCopper = new plateCopper();
		GameRegistry.registerItem(plateCopper, "plateCopper");
				plateDysprosium = new plateDysprosium();
		GameRegistry.registerItem(plateDysprosium, "plateDysprosium");
				plateErbium = new plateErbium();
		GameRegistry.registerItem(plateErbium, "plateErbium");
				plateEuropium = new plateEuropium();
		GameRegistry.registerItem(plateEuropium, "plateEuropium");
				plateGadolinium = new plateGadolinium();
		GameRegistry.registerItem(plateGadolinium, "plateGadolinium");
				plateGallium = new plateGallium();
		GameRegistry.registerItem(plateGallium, "plateGallium");
				plateGermanium = new plateGermanium();
		GameRegistry.registerItem(plateGermanium, "plateGermanium");
				plateGold = new plateGold();
		GameRegistry.registerItem(plateGold, "plateGold");
				plateHafnium = new plateHafnium();
		GameRegistry.registerItem(plateHafnium, "plateHafnium");
				plateHolmium = new plateHolmium();
		GameRegistry.registerItem(plateHolmium, "plateHolmium");
				plateIndium = new plateIndium();
		GameRegistry.registerItem(plateIndium, "plateIndium");
				plateIodine = new plateIodine();
		GameRegistry.registerItem(plateIodine, "plateIodine");
				plateIridium = new plateIridium();
		GameRegistry.registerItem(plateIridium, "plateIridium");
				plateIron = new plateIron();
		GameRegistry.registerItem(plateIron, "plateIron");
				plateKrypton = new plateKrypton();
		GameRegistry.registerItem(plateKrypton, "plateKrypton");
				plateLanthanum = new plateLanthanum();
		GameRegistry.registerItem(plateLanthanum, "plateLanthanum");
				plateLead = new plateLead();
		GameRegistry.registerItem(plateLead, "plateLead");
				plateLithium = new plateLithium();
		GameRegistry.registerItem(plateLithium, "plateLithium");
				plateLutetium = new plateLutetium();
		GameRegistry.registerItem(plateLutetium, "plateLutetium");
				plateMagnesium = new plateMagnesium();
		GameRegistry.registerItem(plateMagnesium, "plateMagnesium");
				plateManganese = new plateManganese();
		GameRegistry.registerItem(plateManganese, "plateManganese");
				plateMercury = new plateMercury();
		GameRegistry.registerItem(plateMercury, "plateMercury");
				plateMolybdenum = new plateMolybdenum();
		GameRegistry.registerItem(plateMolybdenum, "plateMolybdenum");
				plateNeodymium = new plateNeodymium();
		GameRegistry.registerItem(plateNeodymium, "plateNeodymium");
				plateNickel = new plateNickel();
		GameRegistry.registerItem(plateNickel, "plateNickel");
				plateNiobium = new plateNiobium();
		GameRegistry.registerItem(plateNiobium, "plateNiobium");
				plateOsmium = new plateOsmium();
		GameRegistry.registerItem(plateOsmium, "plateOsmium");
				platePalladium = new platePalladium();
		GameRegistry.registerItem(platePalladium, "platePalladium");
				platePhosphorus = new platePhosphorus();
		GameRegistry.registerItem(platePhosphorus, "platePhosphorus");
				platePlatinum = new platePlatinum();
		GameRegistry.registerItem(platePlatinum, "platePlatinum");
				platePolonium = new platePolonium();
		GameRegistry.registerItem(platePolonium, "platePolonium");
				platePotassium = new platePotassium();
		GameRegistry.registerItem(platePotassium, "platePotassium");
				platePraseodymium = new platePraseodymium();
		GameRegistry.registerItem(platePraseodymium, "platePraseodymium");
				plateProtactinium = new plateProtactinium();
		GameRegistry.registerItem(plateProtactinium, "plateProtactinium");
				plateRadium = new plateRadium();
		GameRegistry.registerItem(plateRadium, "plateRadium");
				plateRhenium = new plateRhenium();
		GameRegistry.registerItem(plateRhenium, "plateRhenium");
				plateRhodium = new plateRhodium();
		GameRegistry.registerItem(plateRhodium, "plateRhodium");
				plateRubidium = new plateRubidium();
		GameRegistry.registerItem(plateRubidium, "plateRubidium");
				plateRuthenium = new plateRuthenium();
		GameRegistry.registerItem(plateRuthenium, "plateRuthenium");
				plateSamarium = new plateSamarium();
		GameRegistry.registerItem(plateSamarium, "plateSamarium");
				plateScandium = new plateScandium();
		GameRegistry.registerItem(plateScandium, "plateScandium");
				plateSelenium = new plateSelenium();
		GameRegistry.registerItem(plateSelenium, "plateSelenium");
				plateSilicon = new plateSilicon();
		GameRegistry.registerItem(plateSilicon, "plateSilicon");
				plateSilver = new plateSilver();
		GameRegistry.registerItem(plateSilver, "plateSilver");
				plateSodium = new plateSodium();
		GameRegistry.registerItem(plateSodium, "plateSodium");
				plateStrontium = new plateStrontium();
		GameRegistry.registerItem(plateStrontium, "plateStrontium");
				plateSulfur = new plateSulfur();
		GameRegistry.registerItem(plateSulfur, "plateSulfur");
				plateTantalum = new plateTantalum();
		GameRegistry.registerItem(plateTantalum, "plateTantalum");
				plateTellurium = new plateTellurium();
		GameRegistry.registerItem(plateTellurium, "plateTellurium");
				plateTerbium = new plateTerbium();
		GameRegistry.registerItem(plateTerbium, "plateTerbium");
				plateThallium = new plateThallium();
		GameRegistry.registerItem(plateThallium, "plateThallium");
				plateThorium = new plateThorium();
		GameRegistry.registerItem(plateThorium, "plateThorium");
				plateThulium = new plateThulium();
		GameRegistry.registerItem(plateThulium, "plateThulium");
				plateTin = new plateTin();
		GameRegistry.registerItem(plateTin, "plateTin");
				plateTitanium = new plateTitanium();
		GameRegistry.registerItem(plateTitanium, "plateTitanium");
				plateTungsten = new plateTungsten();
		GameRegistry.registerItem(plateTungsten, "plateTungsten");
				plateUranium = new plateUranium();
		GameRegistry.registerItem(plateUranium, "plateUranium");
				plateVanadium = new plateVanadium();
		GameRegistry.registerItem(plateVanadium, "plateVanadium");
				plateYtterbium = new plateYtterbium();
		GameRegistry.registerItem(plateYtterbium, "plateYtterbium");
				plateYttrium = new plateYttrium();
		GameRegistry.registerItem(plateYttrium, "plateYttrium");
				plateZinc = new plateZinc();
		GameRegistry.registerItem(plateZinc, "plateZinc");
				plateZirconium = new plateZirconium();
		GameRegistry.registerItem(plateZirconium, "plateZirconium");
			}
}
