package me.tomkent.chemcraft;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;


public class ItemLoader {
		public static Item dustActinium;
		public static Item dustAluminium;
		public static Item dustAntimony;
		public static Item dustArsenic;
		public static Item dustBarium;
		public static Item dustBeryllium;
		public static Item dustBismuth;
		public static Item dustBoron;
		public static Item dustCadmium;
		public static Item dustCaesium;
		public static Item dustCalcium;
		public static Item dustCarbon;
		public static Item dustCerium;
		public static Item dustChromium;
		public static Item dustCobalt;
		public static Item dustCopper;
		public static Item dustDysprosium;
		public static Item dustErbium;
		public static Item dustEuropium;
		public static Item dustGadolinium;
		public static Item dustGallium;
		public static Item dustGermanium;
		public static Item dustGold;
		public static Item dustHafnium;
		public static Item dustHolmium;
		public static Item dustIndium;
		public static Item dustIodine;
		public static Item dustIridium;
		public static Item dustIron;
		public static Item dustKrypton;
		public static Item dustLanthanum;
		public static Item dustLead;
		public static Item dustLithium;
		public static Item dustLutetium;
		public static Item dustMagnesium;
		public static Item dustManganese;
		public static Item dustMercury;
		public static Item dustMolybdenum;
		public static Item dustNeodymium;
		public static Item dustNickel;
		public static Item dustNiobium;
		public static Item dustOsmium;
		public static Item dustPalladium;
		public static Item dustPhosphorus;
		public static Item dustPlatinum;
		public static Item dustPolonium;
		public static Item dustPotassium;
		public static Item dustPraseodymium;
		public static Item dustProtactinium;
		public static Item dustRadium;
		public static Item dustRhenium;
		public static Item dustRhodium;
		public static Item dustRubidium;
		public static Item dustRuthenium;
		public static Item dustSamarium;
		public static Item dustScandium;
		public static Item dustSelenium;
		public static Item dustSilicon;
		public static Item dustSilver;
		public static Item dustSodium;
		public static Item dustStrontium;
		public static Item dustSulfur;
		public static Item dustTantalum;
		public static Item dustTellurium;
		public static Item dustTerbium;
		public static Item dustThallium;
		public static Item dustThorium;
		public static Item dustThulium;
		public static Item dustTin;
		public static Item dustTitanium;
		public static Item dustTungsten;
		public static Item dustUranium;
		public static Item dustVanadium;
		public static Item dustYtterbium;
		public static Item dustYttrium;
		public static Item dustZinc;
		public static Item dustZirconium;
		public static Item ingotActinium;
		public static Item ingotAluminium;
		public static Item ingotAntimony;
		public static Item ingotArsenic;
		public static Item ingotBarium;
		public static Item ingotBeryllium;
		public static Item ingotBismuth;
		public static Item ingotBoron;
		public static Item ingotCadmium;
		public static Item ingotCaesium;
		public static Item ingotCalcium;
		public static Item ingotCerium;
		public static Item ingotChromium;
		public static Item ingotCobalt;
		public static Item ingotCopper;
		public static Item ingotDysprosium;
		public static Item ingotErbium;
		public static Item ingotEuropium;
		public static Item ingotGadolinium;
		public static Item ingotGallium;
		public static Item ingotGermanium;
		public static Item ingotGold;
		public static Item ingotHafnium;
		public static Item ingotHolmium;
		public static Item ingotIndium;
		public static Item ingotIodine;
		public static Item ingotIridium;
		public static Item ingotIron;
		public static Item ingotKrypton;
		public static Item ingotLanthanum;
		public static Item ingotLead;
		public static Item ingotLithium;
		public static Item ingotLutetium;
		public static Item ingotMagnesium;
		public static Item ingotManganese;
		public static Item ingotMercury;
		public static Item ingotMolybdenum;
		public static Item ingotNeodymium;
		public static Item ingotNickel;
		public static Item ingotNiobium;
		public static Item ingotOsmium;
		public static Item ingotPalladium;
		public static Item ingotPhosphorus;
		public static Item ingotPlatinum;
		public static Item ingotPolonium;
		public static Item ingotPotassium;
		public static Item ingotPraseodymium;
		public static Item ingotProtactinium;
		public static Item ingotRadium;
		public static Item ingotRhenium;
		public static Item ingotRhodium;
		public static Item ingotRubidium;
		public static Item ingotRuthenium;
		public static Item ingotSamarium;
		public static Item ingotScandium;
		public static Item ingotSelenium;
		public static Item ingotSilicon;
		public static Item ingotSilver;
		public static Item ingotSodium;
		public static Item ingotStrontium;
		public static Item ingotTantalum;
		public static Item ingotTellurium;
		public static Item ingotTerbium;
		public static Item ingotThallium;
		public static Item ingotThorium;
		public static Item ingotThulium;
		public static Item ingotTin;
		public static Item ingotTitanium;
		public static Item ingotTungsten;
		public static Item ingotUranium;
		public static Item ingotVanadium;
		public static Item ingotYtterbium;
		public static Item ingotYttrium;
		public static Item ingotZinc;
		public static Item ingotZirconium;
		public static Item plateActinium;
		public static Item plateAluminium;
		public static Item plateAntimony;
		public static Item plateArsenic;
		public static Item plateBarium;
		public static Item plateBeryllium;
		public static Item plateBismuth;
		public static Item plateBoron;
		public static Item plateCadmium;
		public static Item plateCaesium;
		public static Item plateCarbon;
		public static Item plateCerium;
		public static Item plateChromium;
		public static Item plateCobalt;
		public static Item plateCopper;
		public static Item plateDysprosium;
		public static Item plateErbium;
		public static Item plateEuropium;
		public static Item plateGadolinium;
		public static Item plateGallium;
		public static Item plateGermanium;
		public static Item plateGold;
		public static Item plateHafnium;
		public static Item plateHolmium;
		public static Item plateIndium;
		public static Item plateIodine;
		public static Item plateIridium;
		public static Item plateIron;
		public static Item plateKrypton;
		public static Item plateLanthanum;
		public static Item plateLead;
		public static Item plateLithium;
		public static Item plateLutetium;
		public static Item plateMagnesium;
		public static Item plateManganese;
		public static Item plateMercury;
		public static Item plateMolybdenum;
		public static Item plateNeodymium;
		public static Item plateNickel;
		public static Item plateNiobium;
		public static Item plateOsmium;
		public static Item platePalladium;
		public static Item platePhosphorus;
		public static Item platePlatinum;
		public static Item platePolonium;
		public static Item platePotassium;
		public static Item platePraseodymium;
		public static Item plateProtactinium;
		public static Item plateRadium;
		public static Item plateRhenium;
		public static Item plateRhodium;
		public static Item plateRubidium;
		public static Item plateRuthenium;
		public static Item plateSamarium;
		public static Item plateScandium;
		public static Item plateSelenium;
		public static Item plateSilicon;
		public static Item plateSilver;
		public static Item plateSodium;
		public static Item plateStrontium;
		public static Item plateSulfur;
		public static Item plateTantalum;
		public static Item plateTellurium;
		public static Item plateTerbium;
		public static Item plateThallium;
		public static Item plateThorium;
		public static Item plateThulium;
		public static Item plateTin;
		public static Item plateTitanium;
		public static Item plateTungsten;
		public static Item plateUranium;
		public static Item plateVanadium;
		public static Item plateYtterbium;
		public static Item plateYttrium;
		public static Item plateZinc;
		public static Item plateZirconium;
		public static Item plateMachine;
		
	
	public static void initItems() {
				dustActinium = new GenericItem("dustActinium","dustActinium","Actinium dust", 64);
		GameRegistry.registerItem(dustActinium, "Actinium dust");
				dustAluminium = new GenericItem("dustAluminium","dustAluminium","Aluminium dust", 64);
		GameRegistry.registerItem(dustAluminium, "Aluminium dust");
				dustAntimony = new GenericItem("dustAntimony","dustAntimony","Antimony dust", 64);
		GameRegistry.registerItem(dustAntimony, "Antimony dust");
				dustArsenic = new GenericItem("dustArsenic","dustArsenic","Arsenic dust", 64);
		GameRegistry.registerItem(dustArsenic, "Arsenic dust");
				dustBarium = new GenericItem("dustBarium","dustBarium","Barium dust", 64);
		GameRegistry.registerItem(dustBarium, "Barium dust");
				dustBeryllium = new GenericItem("dustBeryllium","dustBeryllium","Beryllium dust", 64);
		GameRegistry.registerItem(dustBeryllium, "Beryllium dust");
				dustBismuth = new GenericItem("dustBismuth","dustBismuth","Bismuth dust", 64);
		GameRegistry.registerItem(dustBismuth, "Bismuth dust");
				dustBoron = new GenericItem("dustBoron","dustBoron","Boron dust", 64);
		GameRegistry.registerItem(dustBoron, "Boron dust");
				dustCadmium = new GenericItem("dustCadmium","dustCadmium","Cadmium dust", 64);
		GameRegistry.registerItem(dustCadmium, "Cadmium dust");
				dustCaesium = new GenericItem("dustCaesium","dustCaesium","Caesium dust", 64);
		GameRegistry.registerItem(dustCaesium, "Caesium dust");
				dustCalcium = new GenericItem("dustCalcium","dustCalcium","Calcium dust", 64);
		GameRegistry.registerItem(dustCalcium, "Calcium dust");
				dustCarbon = new GenericItem("dustCarbon","dustCarbon","Carbon dust", 64);
		GameRegistry.registerItem(dustCarbon, "Carbon dust");
				dustCerium = new GenericItem("dustCerium","dustCerium","Cerium dust", 64);
		GameRegistry.registerItem(dustCerium, "Cerium dust");
				dustChromium = new GenericItem("dustChromium","dustChromium","Chromium dust", 64);
		GameRegistry.registerItem(dustChromium, "Chromium dust");
				dustCobalt = new GenericItem("dustCobalt","dustCobalt","Cobalt dust", 64);
		GameRegistry.registerItem(dustCobalt, "Cobalt dust");
				dustCopper = new GenericItem("dustCopper","dustCopper","Copper dust", 64);
		GameRegistry.registerItem(dustCopper, "Copper dust");
				dustDysprosium = new GenericItem("dustDysprosium","dustDysprosium","Dysprosium dust", 64);
		GameRegistry.registerItem(dustDysprosium, "Dysprosium dust");
				dustErbium = new GenericItem("dustErbium","dustErbium","Erbium dust", 64);
		GameRegistry.registerItem(dustErbium, "Erbium dust");
				dustEuropium = new GenericItem("dustEuropium","dustEuropium","Europium dust", 64);
		GameRegistry.registerItem(dustEuropium, "Europium dust");
				dustGadolinium = new GenericItem("dustGadolinium","dustGadolinium","Gadolinium dust", 64);
		GameRegistry.registerItem(dustGadolinium, "Gadolinium dust");
				dustGallium = new GenericItem("dustGallium","dustGallium","Gallium dust", 64);
		GameRegistry.registerItem(dustGallium, "Gallium dust");
				dustGermanium = new GenericItem("dustGermanium","dustGermanium","Germanium dust", 64);
		GameRegistry.registerItem(dustGermanium, "Germanium dust");
				dustGold = new GenericItem("dustGold","dustGold","Gold dust", 64);
		GameRegistry.registerItem(dustGold, "Gold dust");
				dustHafnium = new GenericItem("dustHafnium","dustHafnium","Hafnium dust", 64);
		GameRegistry.registerItem(dustHafnium, "Hafnium dust");
				dustHolmium = new GenericItem("dustHolmium","dustHolmium","Holmium dust", 64);
		GameRegistry.registerItem(dustHolmium, "Holmium dust");
				dustIndium = new GenericItem("dustIndium","dustIndium","Indium dust", 64);
		GameRegistry.registerItem(dustIndium, "Indium dust");
				dustIodine = new GenericItem("dustIodine","dustIodine","Iodine dust", 64);
		GameRegistry.registerItem(dustIodine, "Iodine dust");
				dustIridium = new GenericItem("dustIridium","dustIridium","Iridium dust", 64);
		GameRegistry.registerItem(dustIridium, "Iridium dust");
				dustIron = new GenericItem("dustIron","dustIron","Iron dust", 64);
		GameRegistry.registerItem(dustIron, "Iron dust");
				dustKrypton = new GenericItem("dustKrypton","dustKrypton","Krypton dust", 64);
		GameRegistry.registerItem(dustKrypton, "Krypton dust");
				dustLanthanum = new GenericItem("dustLanthanum","dustLanthanum","Lanthanum dust", 64);
		GameRegistry.registerItem(dustLanthanum, "Lanthanum dust");
				dustLead = new GenericItem("dustLead","dustLead","Lead dust", 64);
		GameRegistry.registerItem(dustLead, "Lead dust");
				dustLithium = new GenericItem("dustLithium","dustLithium","Lithium dust", 64);
		GameRegistry.registerItem(dustLithium, "Lithium dust");
				dustLutetium = new GenericItem("dustLutetium","dustLutetium","Lutetium dust", 64);
		GameRegistry.registerItem(dustLutetium, "Lutetium dust");
				dustMagnesium = new GenericItem("dustMagnesium","dustMagnesium","Magnesium dust", 64);
		GameRegistry.registerItem(dustMagnesium, "Magnesium dust");
				dustManganese = new GenericItem("dustManganese","dustManganese","Manganese dust", 64);
		GameRegistry.registerItem(dustManganese, "Manganese dust");
				dustMercury = new GenericItem("dustMercury","dustMercury","Mercury dust", 64);
		GameRegistry.registerItem(dustMercury, "Mercury dust");
				dustMolybdenum = new GenericItem("dustMolybdenum","dustMolybdenum","Molybdenum dust", 64);
		GameRegistry.registerItem(dustMolybdenum, "Molybdenum dust");
				dustNeodymium = new GenericItem("dustNeodymium","dustNeodymium","Neodymium dust", 64);
		GameRegistry.registerItem(dustNeodymium, "Neodymium dust");
				dustNickel = new GenericItem("dustNickel","dustNickel","Nickel dust", 64);
		GameRegistry.registerItem(dustNickel, "Nickel dust");
				dustNiobium = new GenericItem("dustNiobium","dustNiobium","Niobium dust", 64);
		GameRegistry.registerItem(dustNiobium, "Niobium dust");
				dustOsmium = new GenericItem("dustOsmium","dustOsmium","Osmium dust", 64);
		GameRegistry.registerItem(dustOsmium, "Osmium dust");
				dustPalladium = new GenericItem("dustPalladium","dustPalladium","Palladium dust", 64);
		GameRegistry.registerItem(dustPalladium, "Palladium dust");
				dustPhosphorus = new GenericItem("dustPhosphorus","dustPhosphorus","Phosphorus dust", 64);
		GameRegistry.registerItem(dustPhosphorus, "Phosphorus dust");
				dustPlatinum = new GenericItem("dustPlatinum","dustPlatinum","Platinum dust", 64);
		GameRegistry.registerItem(dustPlatinum, "Platinum dust");
				dustPolonium = new GenericItem("dustPolonium","dustPolonium","Polonium dust", 64);
		GameRegistry.registerItem(dustPolonium, "Polonium dust");
				dustPotassium = new GenericItem("dustPotassium","dustPotassium","Potassium dust", 64);
		GameRegistry.registerItem(dustPotassium, "Potassium dust");
				dustPraseodymium = new GenericItem("dustPraseodymium","dustPraseodymium","Praseodymium dust", 64);
		GameRegistry.registerItem(dustPraseodymium, "Praseodymium dust");
				dustProtactinium = new GenericItem("dustProtactinium","dustProtactinium","Protactinium dust", 64);
		GameRegistry.registerItem(dustProtactinium, "Protactinium dust");
				dustRadium = new GenericItem("dustRadium","dustRadium","Radium dust", 64);
		GameRegistry.registerItem(dustRadium, "Radium dust");
				dustRhenium = new GenericItem("dustRhenium","dustRhenium","Rhenium dust", 64);
		GameRegistry.registerItem(dustRhenium, "Rhenium dust");
				dustRhodium = new GenericItem("dustRhodium","dustRhodium","Rhodium dust", 64);
		GameRegistry.registerItem(dustRhodium, "Rhodium dust");
				dustRubidium = new GenericItem("dustRubidium","dustRubidium","Rubidium dust", 64);
		GameRegistry.registerItem(dustRubidium, "Rubidium dust");
				dustRuthenium = new GenericItem("dustRuthenium","dustRuthenium","Ruthenium dust", 64);
		GameRegistry.registerItem(dustRuthenium, "Ruthenium dust");
				dustSamarium = new GenericItem("dustSamarium","dustSamarium","Samarium dust", 64);
		GameRegistry.registerItem(dustSamarium, "Samarium dust");
				dustScandium = new GenericItem("dustScandium","dustScandium","Scandium dust", 64);
		GameRegistry.registerItem(dustScandium, "Scandium dust");
				dustSelenium = new GenericItem("dustSelenium","dustSelenium","Selenium dust", 64);
		GameRegistry.registerItem(dustSelenium, "Selenium dust");
				dustSilicon = new GenericItem("dustSilicon","dustSilicon","Silicon dust", 64);
		GameRegistry.registerItem(dustSilicon, "Silicon dust");
				dustSilver = new GenericItem("dustSilver","dustSilver","Silver dust", 64);
		GameRegistry.registerItem(dustSilver, "Silver dust");
				dustSodium = new GenericItem("dustSodium","dustSodium","Sodium dust", 64);
		GameRegistry.registerItem(dustSodium, "Sodium dust");
				dustStrontium = new GenericItem("dustStrontium","dustStrontium","Strontium dust", 64);
		GameRegistry.registerItem(dustStrontium, "Strontium dust");
				dustSulfur = new GenericItem("dustSulfur","dustSulfur","Sulfur dust", 64);
		GameRegistry.registerItem(dustSulfur, "Sulfur dust");
				dustTantalum = new GenericItem("dustTantalum","dustTantalum","Tantalum dust", 64);
		GameRegistry.registerItem(dustTantalum, "Tantalum dust");
				dustTellurium = new GenericItem("dustTellurium","dustTellurium","Tellurium dust", 64);
		GameRegistry.registerItem(dustTellurium, "Tellurium dust");
				dustTerbium = new GenericItem("dustTerbium","dustTerbium","Terbium dust", 64);
		GameRegistry.registerItem(dustTerbium, "Terbium dust");
				dustThallium = new GenericItem("dustThallium","dustThallium","Thallium dust", 64);
		GameRegistry.registerItem(dustThallium, "Thallium dust");
				dustThorium = new GenericItem("dustThorium","dustThorium","Thorium dust", 64);
		GameRegistry.registerItem(dustThorium, "Thorium dust");
				dustThulium = new GenericItem("dustThulium","dustThulium","Thulium dust", 64);
		GameRegistry.registerItem(dustThulium, "Thulium dust");
				dustTin = new GenericItem("dustTin","dustTin","Tin dust", 64);
		GameRegistry.registerItem(dustTin, "Tin dust");
				dustTitanium = new GenericItem("dustTitanium","dustTitanium","Titanium dust", 64);
		GameRegistry.registerItem(dustTitanium, "Titanium dust");
				dustTungsten = new GenericItem("dustTungsten","dustTungsten","Tungsten dust", 64);
		GameRegistry.registerItem(dustTungsten, "Tungsten dust");
				dustUranium = new GenericItem("dustUranium","dustUranium","Uranium dust", 64);
		GameRegistry.registerItem(dustUranium, "Uranium dust");
				dustVanadium = new GenericItem("dustVanadium","dustVanadium","Vanadium dust", 64);
		GameRegistry.registerItem(dustVanadium, "Vanadium dust");
				dustYtterbium = new GenericItem("dustYtterbium","dustYtterbium","Ytterbium dust", 64);
		GameRegistry.registerItem(dustYtterbium, "Ytterbium dust");
				dustYttrium = new GenericItem("dustYttrium","dustYttrium","Yttrium dust", 64);
		GameRegistry.registerItem(dustYttrium, "Yttrium dust");
				dustZinc = new GenericItem("dustZinc","dustZinc","Zinc dust", 64);
		GameRegistry.registerItem(dustZinc, "Zinc dust");
				dustZirconium = new GenericItem("dustZirconium","dustZirconium","Zirconium dust", 64);
		GameRegistry.registerItem(dustZirconium, "Zirconium dust");
				ingotActinium = new GenericItem("ingotActinium","ingotActinium","Actinium ingot", 64);
		GameRegistry.registerItem(ingotActinium, "Actinium ingot");
				ingotAluminium = new GenericItem("ingotAluminium","ingotAluminium","Aluminium ingot", 64);
		GameRegistry.registerItem(ingotAluminium, "Aluminium ingot");
				ingotAntimony = new GenericItem("ingotAntimony","ingotAntimony","Antimony ingot", 64);
		GameRegistry.registerItem(ingotAntimony, "Antimony ingot");
				ingotArsenic = new GenericItem("ingotArsenic","ingotArsenic","Arsenic ingot", 64);
		GameRegistry.registerItem(ingotArsenic, "Arsenic ingot");
				ingotBarium = new GenericItem("ingotBarium","ingotBarium","Barium ingot", 64);
		GameRegistry.registerItem(ingotBarium, "Barium ingot");
				ingotBeryllium = new GenericItem("ingotBeryllium","ingotBeryllium","Beryllium ingot", 64);
		GameRegistry.registerItem(ingotBeryllium, "Beryllium ingot");
				ingotBismuth = new GenericItem("ingotBismuth","ingotBismuth","Bismuth ingot", 64);
		GameRegistry.registerItem(ingotBismuth, "Bismuth ingot");
				ingotBoron = new GenericItem("ingotBoron","ingotBoron","Boron ingot", 64);
		GameRegistry.registerItem(ingotBoron, "Boron ingot");
				ingotCadmium = new GenericItem("ingotCadmium","ingotCadmium","Cadmium ingot", 64);
		GameRegistry.registerItem(ingotCadmium, "Cadmium ingot");
				ingotCaesium = new GenericItem("ingotCaesium","ingotCaesium","Caesium ingot", 64);
		GameRegistry.registerItem(ingotCaesium, "Caesium ingot");
				ingotCalcium = new GenericItem("ingotCalcium","ingotCalcium","Calcium ingot", 64);
		GameRegistry.registerItem(ingotCalcium, "Calcium ingot");
				ingotCerium = new GenericItem("ingotCerium","ingotCerium","Cerium ingot", 64);
		GameRegistry.registerItem(ingotCerium, "Cerium ingot");
				ingotChromium = new GenericItem("ingotChromium","ingotChromium","Chromium ingot", 64);
		GameRegistry.registerItem(ingotChromium, "Chromium ingot");
				ingotCobalt = new GenericItem("ingotCobalt","ingotCobalt","Cobalt ingot", 64);
		GameRegistry.registerItem(ingotCobalt, "Cobalt ingot");
				ingotCopper = new GenericItem("ingotCopper","ingotCopper","Copper ingot", 64);
		GameRegistry.registerItem(ingotCopper, "Copper ingot");
				ingotDysprosium = new GenericItem("ingotDysprosium","ingotDysprosium","Dysprosium ingot", 64);
		GameRegistry.registerItem(ingotDysprosium, "Dysprosium ingot");
				ingotErbium = new GenericItem("ingotErbium","ingotErbium","Erbium ingot", 64);
		GameRegistry.registerItem(ingotErbium, "Erbium ingot");
				ingotEuropium = new GenericItem("ingotEuropium","ingotEuropium","Europium ingot", 64);
		GameRegistry.registerItem(ingotEuropium, "Europium ingot");
				ingotGadolinium = new GenericItem("ingotGadolinium","ingotGadolinium","Gadolinium ingot", 64);
		GameRegistry.registerItem(ingotGadolinium, "Gadolinium ingot");
				ingotGallium = new GenericItem("ingotGallium","ingotGallium","Gallium ingot", 64);
		GameRegistry.registerItem(ingotGallium, "Gallium ingot");
				ingotGermanium = new GenericItem("ingotGermanium","ingotGermanium","Germanium ingot", 64);
		GameRegistry.registerItem(ingotGermanium, "Germanium ingot");
				ingotGold = new GenericItem("ingotGold","ingotGold","Gold ingot", 64);
		GameRegistry.registerItem(ingotGold, "Gold ingot");
				ingotHafnium = new GenericItem("ingotHafnium","ingotHafnium","Hafnium ingot", 64);
		GameRegistry.registerItem(ingotHafnium, "Hafnium ingot");
				ingotHolmium = new GenericItem("ingotHolmium","ingotHolmium","Holmium ingot", 64);
		GameRegistry.registerItem(ingotHolmium, "Holmium ingot");
				ingotIndium = new GenericItem("ingotIndium","ingotIndium","Indium ingot", 64);
		GameRegistry.registerItem(ingotIndium, "Indium ingot");
				ingotIodine = new GenericItem("ingotIodine","ingotIodine","Iodine ingot", 64);
		GameRegistry.registerItem(ingotIodine, "Iodine ingot");
				ingotIridium = new GenericItem("ingotIridium","ingotIridium","Iridium ingot", 64);
		GameRegistry.registerItem(ingotIridium, "Iridium ingot");
				ingotIron = new GenericItem("ingotIron","ingotIron","Iron ingot", 64);
		GameRegistry.registerItem(ingotIron, "Iron ingot");
				ingotKrypton = new GenericItem("ingotKrypton","ingotKrypton","Krypton ingot", 64);
		GameRegistry.registerItem(ingotKrypton, "Krypton ingot");
				ingotLanthanum = new GenericItem("ingotLanthanum","ingotLanthanum","Lanthanum ingot", 64);
		GameRegistry.registerItem(ingotLanthanum, "Lanthanum ingot");
				ingotLead = new GenericItem("ingotLead","ingotLead","Lead ingot", 64);
		GameRegistry.registerItem(ingotLead, "Lead ingot");
				ingotLithium = new GenericItem("ingotLithium","ingotLithium","Lithium ingot", 64);
		GameRegistry.registerItem(ingotLithium, "Lithium ingot");
				ingotLutetium = new GenericItem("ingotLutetium","ingotLutetium","Lutetium ingot", 64);
		GameRegistry.registerItem(ingotLutetium, "Lutetium ingot");
				ingotMagnesium = new GenericItem("ingotMagnesium","ingotMagnesium","Magnesium ingot", 64);
		GameRegistry.registerItem(ingotMagnesium, "Magnesium ingot");
				ingotManganese = new GenericItem("ingotManganese","ingotManganese","Manganese ingot", 64);
		GameRegistry.registerItem(ingotManganese, "Manganese ingot");
				ingotMercury = new GenericItem("ingotMercury","ingotMercury","Mercury ingot", 64);
		GameRegistry.registerItem(ingotMercury, "Mercury ingot");
				ingotMolybdenum = new GenericItem("ingotMolybdenum","ingotMolybdenum","Molybdenum ingot", 64);
		GameRegistry.registerItem(ingotMolybdenum, "Molybdenum ingot");
				ingotNeodymium = new GenericItem("ingotNeodymium","ingotNeodymium","Neodymium ingot", 64);
		GameRegistry.registerItem(ingotNeodymium, "Neodymium ingot");
				ingotNickel = new GenericItem("ingotNickel","ingotNickel","Nickel ingot", 64);
		GameRegistry.registerItem(ingotNickel, "Nickel ingot");
				ingotNiobium = new GenericItem("ingotNiobium","ingotNiobium","Niobium ingot", 64);
		GameRegistry.registerItem(ingotNiobium, "Niobium ingot");
				ingotOsmium = new GenericItem("ingotOsmium","ingotOsmium","Osmium ingot", 64);
		GameRegistry.registerItem(ingotOsmium, "Osmium ingot");
				ingotPalladium = new GenericItem("ingotPalladium","ingotPalladium","Palladium ingot", 64);
		GameRegistry.registerItem(ingotPalladium, "Palladium ingot");
				ingotPhosphorus = new GenericItem("ingotPhosphorus","ingotPhosphorus","Phosphorus ingot", 64);
		GameRegistry.registerItem(ingotPhosphorus, "Phosphorus ingot");
				ingotPlatinum = new GenericItem("ingotPlatinum","ingotPlatinum","Platinum ingot", 64);
		GameRegistry.registerItem(ingotPlatinum, "Platinum ingot");
				ingotPolonium = new GenericItem("ingotPolonium","ingotPolonium","Polonium ingot", 64);
		GameRegistry.registerItem(ingotPolonium, "Polonium ingot");
				ingotPotassium = new GenericItem("ingotPotassium","ingotPotassium","Potassium ingot", 64);
		GameRegistry.registerItem(ingotPotassium, "Potassium ingot");
				ingotPraseodymium = new GenericItem("ingotPraseodymium","ingotPraseodymium","Praseodymium ingot", 64);
		GameRegistry.registerItem(ingotPraseodymium, "Praseodymium ingot");
				ingotProtactinium = new GenericItem("ingotProtactinium","ingotProtactinium","Protactinium ingot", 64);
		GameRegistry.registerItem(ingotProtactinium, "Protactinium ingot");
				ingotRadium = new GenericItem("ingotRadium","ingotRadium","Radium ingot", 64);
		GameRegistry.registerItem(ingotRadium, "Radium ingot");
				ingotRhenium = new GenericItem("ingotRhenium","ingotRhenium","Rhenium ingot", 64);
		GameRegistry.registerItem(ingotRhenium, "Rhenium ingot");
				ingotRhodium = new GenericItem("ingotRhodium","ingotRhodium","Rhodium ingot", 64);
		GameRegistry.registerItem(ingotRhodium, "Rhodium ingot");
				ingotRubidium = new GenericItem("ingotRubidium","ingotRubidium","Rubidium ingot", 64);
		GameRegistry.registerItem(ingotRubidium, "Rubidium ingot");
				ingotRuthenium = new GenericItem("ingotRuthenium","ingotRuthenium","Ruthenium ingot", 64);
		GameRegistry.registerItem(ingotRuthenium, "Ruthenium ingot");
				ingotSamarium = new GenericItem("ingotSamarium","ingotSamarium","Samarium ingot", 64);
		GameRegistry.registerItem(ingotSamarium, "Samarium ingot");
				ingotScandium = new GenericItem("ingotScandium","ingotScandium","Scandium ingot", 64);
		GameRegistry.registerItem(ingotScandium, "Scandium ingot");
				ingotSelenium = new GenericItem("ingotSelenium","ingotSelenium","Selenium ingot", 64);
		GameRegistry.registerItem(ingotSelenium, "Selenium ingot");
				ingotSilicon = new GenericItem("ingotSilicon","ingotSilicon","Silicon ingot", 64);
		GameRegistry.registerItem(ingotSilicon, "Silicon ingot");
				ingotSilver = new GenericItem("ingotSilver","ingotSilver","Silver ingot", 64);
		GameRegistry.registerItem(ingotSilver, "Silver ingot");
				ingotSodium = new GenericItem("ingotSodium","ingotSodium","Sodium ingot", 64);
		GameRegistry.registerItem(ingotSodium, "Sodium ingot");
				ingotStrontium = new GenericItem("ingotStrontium","ingotStrontium","Strontium ingot", 64);
		GameRegistry.registerItem(ingotStrontium, "Strontium ingot");
				ingotTantalum = new GenericItem("ingotTantalum","ingotTantalum","Tantalum ingot", 64);
		GameRegistry.registerItem(ingotTantalum, "Tantalum ingot");
				ingotTellurium = new GenericItem("ingotTellurium","ingotTellurium","Tellurium ingot", 64);
		GameRegistry.registerItem(ingotTellurium, "Tellurium ingot");
				ingotTerbium = new GenericItem("ingotTerbium","ingotTerbium","Terbium ingot", 64);
		GameRegistry.registerItem(ingotTerbium, "Terbium ingot");
				ingotThallium = new GenericItem("ingotThallium","ingotThallium","Thallium ingot", 64);
		GameRegistry.registerItem(ingotThallium, "Thallium ingot");
				ingotThorium = new GenericItem("ingotThorium","ingotThorium","Thorium ingot", 64);
		GameRegistry.registerItem(ingotThorium, "Thorium ingot");
				ingotThulium = new GenericItem("ingotThulium","ingotThulium","Thulium ingot", 64);
		GameRegistry.registerItem(ingotThulium, "Thulium ingot");
				ingotTin = new GenericItem("ingotTin","ingotTin","Tin ingot", 64);
		GameRegistry.registerItem(ingotTin, "Tin ingot");
				ingotTitanium = new GenericItem("ingotTitanium","ingotTitanium","Titanium ingot", 64);
		GameRegistry.registerItem(ingotTitanium, "Titanium ingot");
				ingotTungsten = new GenericItem("ingotTungsten","ingotTungsten","Tungsten ingot", 64);
		GameRegistry.registerItem(ingotTungsten, "Tungsten ingot");
				ingotUranium = new GenericItem("ingotUranium","ingotUranium","Uranium ingot", 64);
		GameRegistry.registerItem(ingotUranium, "Uranium ingot");
				ingotVanadium = new GenericItem("ingotVanadium","ingotVanadium","Vanadium ingot", 64);
		GameRegistry.registerItem(ingotVanadium, "Vanadium ingot");
				ingotYtterbium = new GenericItem("ingotYtterbium","ingotYtterbium","Ytterbium ingot", 64);
		GameRegistry.registerItem(ingotYtterbium, "Ytterbium ingot");
				ingotYttrium = new GenericItem("ingotYttrium","ingotYttrium","Yttrium ingot", 64);
		GameRegistry.registerItem(ingotYttrium, "Yttrium ingot");
				ingotZinc = new GenericItem("ingotZinc","ingotZinc","Zinc ingot", 64);
		GameRegistry.registerItem(ingotZinc, "Zinc ingot");
				ingotZirconium = new GenericItem("ingotZirconium","ingotZirconium","Zirconium ingot", 64);
		GameRegistry.registerItem(ingotZirconium, "Zirconium ingot");
				plateActinium = new GenericItem("plateActinium","plateActinium","Actinium plate", 64);
		GameRegistry.registerItem(plateActinium, "Actinium plate");
				plateAluminium = new GenericItem("plateAluminium","plateAluminium","Aluminium plate", 64);
		GameRegistry.registerItem(plateAluminium, "Aluminium plate");
				plateAntimony = new GenericItem("plateAntimony","plateAntimony","Antimony plate", 64);
		GameRegistry.registerItem(plateAntimony, "Antimony plate");
				plateArsenic = new GenericItem("plateArsenic","plateArsenic","Arsenic plate", 64);
		GameRegistry.registerItem(plateArsenic, "Arsenic plate");
				plateBarium = new GenericItem("plateBarium","plateBarium","Barium plate", 64);
		GameRegistry.registerItem(plateBarium, "Barium plate");
				plateBeryllium = new GenericItem("plateBeryllium","plateBeryllium","Beryllium plate", 64);
		GameRegistry.registerItem(plateBeryllium, "Beryllium plate");
				plateBismuth = new GenericItem("plateBismuth","plateBismuth","Bismuth plate", 64);
		GameRegistry.registerItem(plateBismuth, "Bismuth plate");
				plateBoron = new GenericItem("plateBoron","plateBoron","Boron plate", 64);
		GameRegistry.registerItem(plateBoron, "Boron plate");
				plateCadmium = new GenericItem("plateCadmium","plateCadmium","Cadmium plate", 64);
		GameRegistry.registerItem(plateCadmium, "Cadmium plate");
				plateCaesium = new GenericItem("plateCaesium","plateCaesium","Caesium plate", 64);
		GameRegistry.registerItem(plateCaesium, "Caesium plate");
				plateCarbon = new GenericItem("plateCarbon","plateCarbon","Carbon plate", 64);
		GameRegistry.registerItem(plateCarbon, "Carbon plate");
				plateCerium = new GenericItem("plateCerium","plateCerium","Cerium plate", 64);
		GameRegistry.registerItem(plateCerium, "Cerium plate");
				plateChromium = new GenericItem("plateChromium","plateChromium","Chromium plate", 64);
		GameRegistry.registerItem(plateChromium, "Chromium plate");
				plateCobalt = new GenericItem("plateCobalt","plateCobalt","Cobalt plate", 64);
		GameRegistry.registerItem(plateCobalt, "Cobalt plate");
				plateCopper = new GenericItem("plateCopper","plateCopper","Copper plate", 64);
		GameRegistry.registerItem(plateCopper, "Copper plate");
				plateDysprosium = new GenericItem("plateDysprosium","plateDysprosium","Dysprosium plate", 64);
		GameRegistry.registerItem(plateDysprosium, "Dysprosium plate");
				plateErbium = new GenericItem("plateErbium","plateErbium","Erbium plate", 64);
		GameRegistry.registerItem(plateErbium, "Erbium plate");
				plateEuropium = new GenericItem("plateEuropium","plateEuropium","Europium plate", 64);
		GameRegistry.registerItem(plateEuropium, "Europium plate");
				plateGadolinium = new GenericItem("plateGadolinium","plateGadolinium","Gadolinium plate", 64);
		GameRegistry.registerItem(plateGadolinium, "Gadolinium plate");
				plateGallium = new GenericItem("plateGallium","plateGallium","Gallium plate", 64);
		GameRegistry.registerItem(plateGallium, "Gallium plate");
				plateGermanium = new GenericItem("plateGermanium","plateGermanium","Germanium plate", 64);
		GameRegistry.registerItem(plateGermanium, "Germanium plate");
				plateGold = new GenericItem("plateGold","plateGold","Gold plate", 64);
		GameRegistry.registerItem(plateGold, "Gold plate");
				plateHafnium = new GenericItem("plateHafnium","plateHafnium","Hafnium plate", 64);
		GameRegistry.registerItem(plateHafnium, "Hafnium plate");
				plateHolmium = new GenericItem("plateHolmium","plateHolmium","Holmium plate", 64);
		GameRegistry.registerItem(plateHolmium, "Holmium plate");
				plateIndium = new GenericItem("plateIndium","plateIndium","Indium plate", 64);
		GameRegistry.registerItem(plateIndium, "Indium plate");
				plateIodine = new GenericItem("plateIodine","plateIodine","Iodine plate", 64);
		GameRegistry.registerItem(plateIodine, "Iodine plate");
				plateIridium = new GenericItem("plateIridium","plateIridium","Iridium plate", 64);
		GameRegistry.registerItem(plateIridium, "Iridium plate");
				plateIron = new GenericItem("plateIron","plateIron","Iron plate", 64);
		GameRegistry.registerItem(plateIron, "Iron plate");
				plateKrypton = new GenericItem("plateKrypton","plateKrypton","Krypton plate", 64);
		GameRegistry.registerItem(plateKrypton, "Krypton plate");
				plateLanthanum = new GenericItem("plateLanthanum","plateLanthanum","Lanthanum plate", 64);
		GameRegistry.registerItem(plateLanthanum, "Lanthanum plate");
				plateLead = new GenericItem("plateLead","plateLead","Lead plate", 64);
		GameRegistry.registerItem(plateLead, "Lead plate");
				plateLithium = new GenericItem("plateLithium","plateLithium","Lithium plate", 64);
		GameRegistry.registerItem(plateLithium, "Lithium plate");
				plateLutetium = new GenericItem("plateLutetium","plateLutetium","Lutetium plate", 64);
		GameRegistry.registerItem(plateLutetium, "Lutetium plate");
				plateMagnesium = new GenericItem("plateMagnesium","plateMagnesium","Magnesium plate", 64);
		GameRegistry.registerItem(plateMagnesium, "Magnesium plate");
				plateManganese = new GenericItem("plateManganese","plateManganese","Manganese plate", 64);
		GameRegistry.registerItem(plateManganese, "Manganese plate");
				plateMercury = new GenericItem("plateMercury","plateMercury","Mercury plate", 64);
		GameRegistry.registerItem(plateMercury, "Mercury plate");
				plateMolybdenum = new GenericItem("plateMolybdenum","plateMolybdenum","Molybdenum plate", 64);
		GameRegistry.registerItem(plateMolybdenum, "Molybdenum plate");
				plateNeodymium = new GenericItem("plateNeodymium","plateNeodymium","Neodymium plate", 64);
		GameRegistry.registerItem(plateNeodymium, "Neodymium plate");
				plateNickel = new GenericItem("plateNickel","plateNickel","Nickel plate", 64);
		GameRegistry.registerItem(plateNickel, "Nickel plate");
				plateNiobium = new GenericItem("plateNiobium","plateNiobium","Niobium plate", 64);
		GameRegistry.registerItem(plateNiobium, "Niobium plate");
				plateOsmium = new GenericItem("plateOsmium","plateOsmium","Osmium plate", 64);
		GameRegistry.registerItem(plateOsmium, "Osmium plate");
				platePalladium = new GenericItem("platePalladium","platePalladium","Palladium plate", 64);
		GameRegistry.registerItem(platePalladium, "Palladium plate");
				platePhosphorus = new GenericItem("platePhosphorus","platePhosphorus","Phosphorus plate", 64);
		GameRegistry.registerItem(platePhosphorus, "Phosphorus plate");
				platePlatinum = new GenericItem("platePlatinum","platePlatinum","Platinum plate", 64);
		GameRegistry.registerItem(platePlatinum, "Platinum plate");
				platePolonium = new GenericItem("platePolonium","platePolonium","Polonium plate", 64);
		GameRegistry.registerItem(platePolonium, "Polonium plate");
				platePotassium = new GenericItem("platePotassium","platePotassium","Potassium plate", 64);
		GameRegistry.registerItem(platePotassium, "Potassium plate");
				platePraseodymium = new GenericItem("platePraseodymium","platePraseodymium","Praseodymium plate", 64);
		GameRegistry.registerItem(platePraseodymium, "Praseodymium plate");
				plateProtactinium = new GenericItem("plateProtactinium","plateProtactinium","Protactinium plate", 64);
		GameRegistry.registerItem(plateProtactinium, "Protactinium plate");
				plateRadium = new GenericItem("plateRadium","plateRadium","Radium plate", 64);
		GameRegistry.registerItem(plateRadium, "Radium plate");
				plateRhenium = new GenericItem("plateRhenium","plateRhenium","Rhenium plate", 64);
		GameRegistry.registerItem(plateRhenium, "Rhenium plate");
				plateRhodium = new GenericItem("plateRhodium","plateRhodium","Rhodium plate", 64);
		GameRegistry.registerItem(plateRhodium, "Rhodium plate");
				plateRubidium = new GenericItem("plateRubidium","plateRubidium","Rubidium plate", 64);
		GameRegistry.registerItem(plateRubidium, "Rubidium plate");
				plateRuthenium = new GenericItem("plateRuthenium","plateRuthenium","Ruthenium plate", 64);
		GameRegistry.registerItem(plateRuthenium, "Ruthenium plate");
				plateSamarium = new GenericItem("plateSamarium","plateSamarium","Samarium plate", 64);
		GameRegistry.registerItem(plateSamarium, "Samarium plate");
				plateScandium = new GenericItem("plateScandium","plateScandium","Scandium plate", 64);
		GameRegistry.registerItem(plateScandium, "Scandium plate");
				plateSelenium = new GenericItem("plateSelenium","plateSelenium","Selenium plate", 64);
		GameRegistry.registerItem(plateSelenium, "Selenium plate");
				plateSilicon = new GenericItem("plateSilicon","plateSilicon","Silicon plate", 64);
		GameRegistry.registerItem(plateSilicon, "Silicon plate");
				plateSilver = new GenericItem("plateSilver","plateSilver","Silver plate", 64);
		GameRegistry.registerItem(plateSilver, "Silver plate");
				plateSodium = new GenericItem("plateSodium","plateSodium","Sodium plate", 64);
		GameRegistry.registerItem(plateSodium, "Sodium plate");
				plateStrontium = new GenericItem("plateStrontium","plateStrontium","Strontium plate", 64);
		GameRegistry.registerItem(plateStrontium, "Strontium plate");
				plateSulfur = new GenericItem("plateSulfur","plateSulfur","Sulfur plate", 64);
		GameRegistry.registerItem(plateSulfur, "Sulfur plate");
				plateTantalum = new GenericItem("plateTantalum","plateTantalum","Tantalum plate", 64);
		GameRegistry.registerItem(plateTantalum, "Tantalum plate");
				plateTellurium = new GenericItem("plateTellurium","plateTellurium","Tellurium plate", 64);
		GameRegistry.registerItem(plateTellurium, "Tellurium plate");
				plateTerbium = new GenericItem("plateTerbium","plateTerbium","Terbium plate", 64);
		GameRegistry.registerItem(plateTerbium, "Terbium plate");
				plateThallium = new GenericItem("plateThallium","plateThallium","Thallium plate", 64);
		GameRegistry.registerItem(plateThallium, "Thallium plate");
				plateThorium = new GenericItem("plateThorium","plateThorium","Thorium plate", 64);
		GameRegistry.registerItem(plateThorium, "Thorium plate");
				plateThulium = new GenericItem("plateThulium","plateThulium","Thulium plate", 64);
		GameRegistry.registerItem(plateThulium, "Thulium plate");
				plateTin = new GenericItem("plateTin","plateTin","Tin plate", 64);
		GameRegistry.registerItem(plateTin, "Tin plate");
				plateTitanium = new GenericItem("plateTitanium","plateTitanium","Titanium plate", 64);
		GameRegistry.registerItem(plateTitanium, "Titanium plate");
				plateTungsten = new GenericItem("plateTungsten","plateTungsten","Tungsten plate", 64);
		GameRegistry.registerItem(plateTungsten, "Tungsten plate");
				plateUranium = new GenericItem("plateUranium","plateUranium","Uranium plate", 64);
		GameRegistry.registerItem(plateUranium, "Uranium plate");
				plateVanadium = new GenericItem("plateVanadium","plateVanadium","Vanadium plate", 64);
		GameRegistry.registerItem(plateVanadium, "Vanadium plate");
				plateYtterbium = new GenericItem("plateYtterbium","plateYtterbium","Ytterbium plate", 64);
		GameRegistry.registerItem(plateYtterbium, "Ytterbium plate");
				plateYttrium = new GenericItem("plateYttrium","plateYttrium","Yttrium plate", 64);
		GameRegistry.registerItem(plateYttrium, "Yttrium plate");
				plateZinc = new GenericItem("plateZinc","plateZinc","Zinc plate", 64);
		GameRegistry.registerItem(plateZinc, "Zinc plate");
				plateZirconium = new GenericItem("plateZirconium","plateZirconium","Zirconium plate", 64);
		GameRegistry.registerItem(plateZirconium, "Zirconium plate");
				plateMachine = new GenericItem("plateMachine","missing","Machine plate", 64);
		GameRegistry.registerItem(plateMachine, "Machine plate");
			}
}
